language: node_js
node_js:
  - "node" # always use the latest; we are only using it as a test runner for now
cache: npm

jobs:
  include:
    - stage: Tests
      name: lint
      script: npm run lint

    - name: unit tests
      script: npm test

    - stage: Deploy
      script:
        - make gen dist
        - cd dist && npm publish
      if: tag IS present
